namespace: stagecraft
nameOverride: ""

image:
  repository: neo4j
  tag: "5.24-community"
  pullPolicy: IfNotPresent


service:
  enabled: true
  port: 7687
  targetPort: 7687

serviceAccount:
  create: true
  roleArn: ""

externalSecret:
  enabled: true
  storeName: stagecraft
  awsSecretName: stagecraft-neo4j-secrets
  refreshInterval: 1h

persistence:
  size: 10Gi
  storageClassName: gp3

env:
  NEO4J_dbms_memory_heap_max__size: 768m
  NEO4J_dbms_memory_pagecache_size: 512m
  NEO4J_PLUGINS: "[]"
  NEO4J_dbms_default__listen__address: "0.0.0.0"

resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: "1"
    memory: 2Gi
